services:
  web:
    build: .
    container_name: Abdu-039
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      db:
        condition: service_healthy
    networks:
      webnet:
        ipv4_address: 192.168.1.39

  db:
    image: mysql:8.0
    container_name: secureweb-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secureweb
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  db_data:
